# -*- coding: utf-8 -*-
"""MNIST Handwritten detection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lpVRTPlSH_Xl9FPUrN0aVh2p08Tqpb7w
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import sklearn

#load the dat
x=pd.read_csv("https://raw.githubusercontent.com/ageron/handson-ml/master/datasets/lifesat/oecd_bli_2015.csv")
x.head()
#gdp_per_capita=pd.read_csv("gdp_per_capita.csv",thousand=',', delimiter='\t',encoding='latin1',na_values"n\a")

from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
import numpy as np
import matplotlib
import matplotlib.pyplot as plt

mnist = fetch_openml('mnist_784')
mnist

X, y=mnist["data"], mnist["target"]
X.shape

y.shape

from sklearn.datasets import fetch_openml
mnist = fetch_openml("mnist_784")
mnist

x, y= mnist['data'],mnist['target']
x.shape

num=np.array(x)

y.shape

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline

import matplotlib
import matplotlib.pyplot as plt

some_digit = num[36000]
some_digit_image = some_digit.reshape(28, 28)

plt.imshow(some_digit_image, cmap=matplotlib.cm.binary, interpolation="nearest")

y[36000]

y